apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  username: bW9uZ28= # This is base64 encode username(mongo)
  password: bW9uZ28= # This is base64 encode password(mongo)
